spring:
  application:
    name: short-link-redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 1
    host: 192.168.125.128
    password: 123456
    port: 6379

short-link:
  redis:
    short-url-expire-time: 48



